using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using Google.Protobuf.WellKnownTypes;

public class RuntimeGenerator
{
    private static readonly MethodInfo[] _runtimeMethods =
        typeof(Runtime).GetMethods(BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public)
            .Where(it => it.GetCustomAttribute<MethodImplAttribute>()?.Value == MethodImplOptions.InternalCall).ToArray();

    public static void GenerateJsLib()
    {
        var builder = new StringBuilder();
        builder.AppendLine("// This file was automatically generated by RuntimeGenerator.cs in Unity");
        builder.AppendLine("mergeInto(LibraryManager.library, {");

        foreach (var method in _runtimeMethods)
        {
        }

    }
}
