# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpcwebunity import service_pb2 as grpcwebunity_dot_service__pb2


class TestServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Unary = channel.unary_unary(
                '/ai.transforms.grpcwebunity.TestService/Unary',
                request_serializer=grpcwebunity_dot_service__pb2.Request.SerializeToString,
                response_deserializer=grpcwebunity_dot_service__pb2.Response.FromString,
                )
        self.ServerStream = channel.unary_stream(
                '/ai.transforms.grpcwebunity.TestService/ServerStream',
                request_serializer=grpcwebunity_dot_service__pb2.Request.SerializeToString,
                response_deserializer=grpcwebunity_dot_service__pb2.Response.FromString,
                )


class TestServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Unary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Unary': grpc.unary_unary_rpc_method_handler(
                    servicer.Unary,
                    request_deserializer=grpcwebunity_dot_service__pb2.Request.FromString,
                    response_serializer=grpcwebunity_dot_service__pb2.Response.SerializeToString,
            ),
            'ServerStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerStream,
                    request_deserializer=grpcwebunity_dot_service__pb2.Request.FromString,
                    response_serializer=grpcwebunity_dot_service__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.transforms.grpcwebunity.TestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Unary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ai.transforms.grpcwebunity.TestService/Unary',
            grpcwebunity_dot_service__pb2.Request.SerializeToString,
            grpcwebunity_dot_service__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServerStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ai.transforms.grpcwebunity.TestService/ServerStream',
            grpcwebunity_dot_service__pb2.Request.SerializeToString,
            grpcwebunity_dot_service__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
