"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from abc import (
    ABCMeta,
    abstractmethod,
)

from grpc import (
    Channel,
    Server,
    ServicerContext,
    UnaryStreamMultiCallable,
    UnaryUnaryMultiCallable,
)

from typing import (
    Iterator,
)


from .service_pb2 import *
class TestServiceStub:
    def __init__(self, channel: Channel) -> None: ...
    Unary:UnaryUnaryMultiCallable[
        Request,
        Response] = ...

    ServerStream:UnaryStreamMultiCallable[
        Request,
        Response] = ...


class TestServiceServicer(metaclass=ABCMeta):
    @abstractmethod
    def Unary(self,
        request: Request,
        context: ServicerContext,
    ) -> Response: ...

    @abstractmethod
    def ServerStream(self,
        request: Request,
        context: ServicerContext,
    ) -> Iterator[Response]: ...


def add_TestServiceServicer_to_server(servicer: TestServiceServicer, server: Server) -> None: ...
